#!/bin/bash

VERSION=1.6.4
PACKAGE=browsh
TOOL=$PACKAGE
DIRECTORY=$(dirname $0)
#!/bin/bash

STORAGES=(/ocean /bil /hive /local)

OPTIONS=""
for STORAGE in "${STORAGES[@]}"
do
  	if [ -d "$STORAGE" ]; then
                OPTIONS=$OPTIONS" -B $STORAGE"
        fi
done

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
